import Foundation

public enum AionCanonicalIndexError: Error, Equatable, Sendable {
    case missingRuntimeIndex
    case unreadableRuntimeIndex
}

public extension AionIndex {
    /// Loads the compact Shell.sign index bundled with OrboCore.
    ///
    /// The artifact is generated by Forge tooling from the canonical Pass 5 tables.
    /// Missing data fails explicitly; Aion never falls back to ephemeris calculation
    /// or infers shell ownership from instantaneous longitude.
    static func canonical() throws -> AionIndex {
        let bundle = Bundle.module
        let candidates: [URL?] = [
            bundle.url(
                forResource: "aion-shell-sign-index-v1",
                withExtension: "json",
                subdirectory: "Resources"
            ),
            bundle.url(
                forResource: "aion-shell-sign-index-v1",
                withExtension: "json"
            ),
        ]
        guard let url = candidates.compactMap({ $0 }).first else {
            throw AionCanonicalIndexError.missingRuntimeIndex
        }
        guard let data = try? Data(contentsOf: url) else {
            throw AionCanonicalIndexError.unreadableRuntimeIndex
        }
        return try decode(data)
    }
}

public extension Aion {
    /// Canonical Ovum construction for ordinary consumers.
    static func canonical() throws -> Aion {
        Aion(index: try .canonical())
    }
}
