extension PartsKleidesCatalogue {
    static let natalHouses07To12: [PartCatalogueEntry] = [
        natalHouse(7, "marriageMenHermes", "Marriage of men a/t Hermes", ["Asc", "Ve", "Sa"], "Asc + Venus - Saturn", "Asc + Venus - Saturn", .same, tradition: "Hermes (as attributed by al-Biruni)"),
        natalHouse(7, "marriageMenValens", "Marriage of men a/t Vettius Valens", ["Asc", "Ve", "Su"], "Asc + Venus - Sun", "Asc + Venus - Sun", .same, tradition: "Vettius Valens (as attributed by al-Biruni)"),
        natalHouse(7, "trickeryMenWomen", "Trickery and deception of men and women", ["Asc", "Ve", "Su"], "Asc + Venus - Sun", "Asc + Venus - Sun", .same),
        natalHouse(7, "intercourseMen", "Intercourse (men with women)", ["Asc", "Ve", "Su"], "Asc + Venus - Sun", "Asc + Venus - Sun", .same),
        natalHouse(7, "marriageWomenHermes", "Marriage of women (Hermes)", ["Asc", "Sa", "Ve"], "Asc + Saturn - Venus", "Asc + Saturn - Venus", .same, tradition: "Hermes (as attributed by al-Biruni)"),
        natalHouse(7, "marriageWomenValens", "Marriage of women (Valens)", ["Asc", "Ma", "Mo"], "Asc + Mars - Moon", "Asc + Mars - Moon", .same, tradition: "Vettius Valens (as attributed by al-Biruni)"),
        natalHouse(7, "misconductByWomen", "Misconduct by women", ["Asc", "Ma", "Mo"], "Asc + Mars - Moon", "Asc + Mars - Moon", .same),
        natalHouse(7, "trickeryMenByWomen", "Trickery and deceit of men by women", ["Asc", "Ma", "Mo"], "Asc + Mars - Moon", "Asc + Mars - Moon", .same),
        natalHouse(7, "intercourseWomen", "Intercourse (women with men)", ["Asc", "Ma", "Mo"], "Asc + Mars - Moon", "Asc + Mars - Moon", .same),
        natalHouse(7, "unchastityOfWomen", "Unchastity of women", ["Asc", "Ma", "Mo"], "Asc + Mars - Moon", "Asc + Mars - Moon", .same),
        natalHouse(7, "chastityOfWomen", "Chastity of women", ["Asc", "Ve", "Mo"], "Asc + Venus - Moon", "Asc + Venus - Moon", .same),
        natalHouse(7, "marriageMenWomenHermes", "Marriage of men and women a/t Hermes", ["Asc", "c7", "Ve"], "Asc + Cusp of 7th - Venus", "Asc + Cusp of 7th - Venus", .same, tradition: "Hermes (as attributed by al-Biruni)"),
        natalHouse(7, "timeOfMarriageHermes", "Time of marriage (Hermes)", ["Asc", "Mo", "Su"], "Asc + Moon - Sun", "Asc + Moon - Sun", .same, tradition: "Hermes (as attributed by al-Biruni)"),
        natalHouse(7, "fraudulentMarriage", "Fraudulent marriage & Facilitating it", ["Asc", "Ve", "Sa"], "Asc + Venus - Saturn", "Asc + Venus - Saturn", .same),
        natalHouse(7, "sonsInLaw", "Sons in law", ["Asc", "Ve", "Sa"], "Asc + Venus - Saturn", "Asc + Saturn - Venus", .reverse),
        natalHouse(7, "lawsuits", "Lawsuits", ["Asc", "Ju", "Ma"], "Asc + Jupiter - Mars", "Asc + Mars - Jupiter", .reverse),

        natalHouse(8, "death", "Death", ["SaturnDegree", "c8", "Mo"], "Degree of Saturn + Cusp of 8th - Moon", "Degree of Saturn + Cusp of 8th - Moon", .same),
        natalHouse(8, "anairetai", "Anairetai [anareta: destroyer]", ["Asc", "Mo", "LordAsc"], "Asc + Moon - Lord of Asc", "Asc + Lord of Asc - Moon", .reverse),
        natalHouse(8, "yearFearedForDeathFamine", "Year to be feared at birth for death, famine", ["Asc", "LastSyzygyDispositor", "Sa"], "Asc + dispositor of last syzygy - Saturn", "Asc + dispositor of last syzygy - Saturn", .same),
        natalHouse(8, "placeOfMurderAndSickness", "Place of murder and sickness", ["MercuryDegree", "Ma", "Sa"], "Degree of Mercury + Mars - Saturn", "Degree of Mercury + Saturn - Mars", .reverse),
        natalHouse(8, "dangerOfViolence", "Danger of violence", ["Asc", "Me", "Sa"], "Asc + Mercury - Saturn", "Asc + Saturn - Mercury", .reverse),

        natalHouse(9, "journeys", "Journeys", ["Asc", "c9", "L9"], "Asc + Cusp of 9th - Lord of 9th", "Asc + Cusp of 9th - Lord of 9th", .same),
        natalHouse(9, "byWater", "By water", ["Asc", "Cancer15", "Sa"], "Asc + 15 Cancer - Saturn", "Asc + Saturn - 15 Cancer", .reverse),
        natalHouse(9, "timidityAndHiding", "Timidity and hiding", ["Asc", "Me", "Mo"], "Asc + Mercury - Moon", "Asc + Moon - Mercury", .reverse),
        natalHouse(9, "deepReflection", "Deep reflection", ["Asc", "Mo", "Sa"], "Asc + Moon - Saturn", "Asc + Saturn - Moon", .reverse),
        natalHouse(9, "understandingAndWisdom", "Understanding and wisdom", ["Asc", "Su", "Sa"], "Asc + Sun - Saturn", "Asc + Saturn - Sun", .reverse),
        natalHouse(9, "traditionsKnowledgeAffairs", "Traditions, knowledge of affairs", ["Asc", "Ju", "Su"], "Asc + Jupiter - Sun", "Asc + Sun - Jupiter", .reverse),
        natalHouse(9, "knowledgeTrueFalse", "Knowledge whether true or false", ["Asc", "Mo", "Me"], "Asc + Moon - Mercury", "Asc + Moon - Mercury", .same),

        natalHouse(10, "nobleBirths", "Noble births", ["Asc", "LordOfTimeExaltationDegree", "LordOfTime"], "Asc + Degree of exaltation of the lord of time - lord of time", "Asc + lord of time - Degree of exaltation of the lord of time", .reverse),
        natalHouse(10, "kingsAndSultans", "Kings and Sultans", ["unresolved"], "unresolved", "unresolved", .reverse, status: .unresolved),
        natalHouse(10, "administratorsVazirs", "Administrators, vazirs [ministers], etc.", ["Asc", "Ma", "Me"], "Asc + Mars - Mercury", "Asc + Mercury - Mars", .reverse),
        natalHouse(10, "sultansVictoryConquest", "Sultan's victory, conquest", ["Asc", "Sa", "Su"], "Asc + Saturn - Sun", "Asc + Sun - Saturn", .reverse),
        natalHouse(10, "riseInStation", "Of those who rise in station", ["Asc", "F", "Sa"], "Asc + Fortune - Saturn", "Asc + Saturn - Fortune", .reverse),
        natalHouse(10, "celebratedRank", "Celebrated persons of rank", ["Asc", "Su", "Sa"], "Asc + Sun - Saturn", "Asc + Sun - Saturn", .same),
        natalHouse(10, "armiesAndPolice", "Armies and police", ["Asc", "Sa", "Ma"], "Asc + Saturn - Mars", "Asc + Mars - Saturn", .reverse),
        natalHouse(10, "sultanNativities", "Sultan. Those concerned In nativities", ["Asc", "Mo", "Sa"], "Asc + Moon - Saturn", "Asc + Moon - Saturn", .same),
        natalHouse(10, "merchantsAndWork", "Merchants and their work", ["Asc", "Ve", "Me"], "Asc + Venus - Mercury", "Asc + Mercury - Venus", .reverse),
        natalHouse(10, "buyingAndSelling", "Buying and selling", ["Asc", "F", "Sp"], "Asc + Fortune - Spirit", "Asc + Spirit - Fortune", .reverse),
        natalHouse(10, "medicalTreatmentOperations", "Operations and orders in medical Treatment", ["Asc", "Ju", "Su"], "Asc + Jupiter - Sun", "Asc + Sun - Jupiter", .reverse),
        natalHouse(10, "mothers", "Mothers", ["Asc", "Mo", "Ve"], "Asc + Moon - Venus", "Asc + Venus - Moon", .reverse),

        natalHouse(11, "glory", "Glory", ["Asc", "Sp", "F"], "Asc + Spirit - Fortune", "Asc + Fortune - Spirit", .reverse),
        natalHouse(11, "friendshipAndEnmity", "Friendship and enmity", ["Asc", "Sp", "F"], "Asc + Spirit - Fortune", "Asc + Fortune - Spirit", .reverse),
        natalHouse(11, "knownAndRevered", "Known by men and revered, Constant in affairs", ["Asc", "Su", "F"], "Asc + Sun - Fortune", "Asc + Fortune - Sun", .reverse),
        natalHouse(11, "success", "Success", ["Asc", "Ju", "F"], "Asc + Jupiter - Fortune", "Asc + Fortune - Jupiter", .reverse),
        natalHouse(11, "worldliness", "Worldliness", ["Asc", "Ve", "F"], "Asc + Venus - Fortune", "Asc + Fortune - Venus", .reverse),
        natalHouse(11, "hope", "Hope", ["Asc", "Me", "Ju"], "Asc + Mercury - Jupiter", "Asc + Jupiter - Mercury", .reverse),
        natalHouse(11, "friends", "Friends", ["Asc", "Me", "Mo"], "Asc + Mercury - Moon", "Asc + Mercury - Moon", .same),
        natalHouse(11, "violence", "Violence", ["Asc", "Me", "Sp"], "Asc + Mercury - Spirit", "Asc + Mercury - Spirit", .same),
        natalHouse(11, "abundanceInHouse", "Abundance in house", ["Asc", "Su", "Mo"], "Asc + Sun - Moon", "Asc + Sun - Moon", .same),
        natalHouse(11, "libertyOfPerson", "Liberty of Person", ["Asc", "Su", "Me"], "Asc + Sun - Mercury", "Asc + Mercury - Sun", .reverse),
        natalHouse(11, "praiseAndAcceptation", "Praise and acceptation", ["Asc", "Ve", "Ju"], "Asc + Venus - Jupiter", "Asc + Jupiter - Venus", .reverse),

        natalHouse(12, "enmityAncients", "Enmity a/t some of the ancients", ["Asc", "Ma", "Sa"], "Asc + Mars - Saturn", "Asc + Mars - Saturn", .same, tradition: "some of the ancients (as attributed by al-Biruni)"),
        natalHouse(12, "enmityHermes", "Enmity a/t Hermes", ["Asc", "c12", "L12"], "Asc + Cusp of 12th - Lord of 12th", "Asc + Cusp of 12th - Lord of 12th", .same, tradition: "Hermes (as attributed by al-Biruni)"),
        natalHouse(12, "badLuck", "Bad luck", ["Asc", "F", "Sp"], "Asc + Fortune - Spirit", "Asc + Fortune - Spirit", .same),
    ]
}
