// Rectification content bank — ingested from huntarfischer/orborectifier (Lunar Lock v2,
// Decan Lock v2). Self-report evidence only; the astronomical candidate set is computed
// live in the DC via spine.ascProbe/bodyProbe and never overridden by these answers.
export const LUNAR_HOUSES = {
  1: { gravity: 'My mood or physical state tends to show on me quickly.', retention: 'Things that feel like part of me or my personal presentation are hard to get rid of.', rhythm: 'My appearance, energy, or sense of myself changes noticeably with my mood or surroundings.', reflex: 'I change something about my body, immediate state, or surroundings.' },
  2: { gravity: 'Not having enough money, belongings, food, or supplies unsettles me quickly.', retention: 'Useful, valuable, or potentially-needed possessions are especially hard for me to get rid of.', rhythm: 'I swing between holding tightly to what I have and being surprisingly loose with it.', reflex: 'I check, organize, save, stock up, or make sure I have enough.' },
  3: { gravity: 'Information, messages, conversations, and what is happening around me constantly pull my attention.', retention: 'Screenshots, documents, messages, links, notes, books, and saved information are hard for me to delete or throw away.', rhythm: 'My attention cycles through messages, reading, conversation, errands, and small pieces of information.', reflex: 'I talk, text, search, read, write, ask questions, or get moving locally.' },
  4: { gravity: 'What happens at home or in my family affects me more deeply than outsiders usually realize.', retention: 'Family photographs, childhood things, keepsakes, and objects tied to where I came from are hardest to let go of.', rhythm: 'My inner state shows up in changes to my home or room, or in recurring family and memory patterns.', reflex: 'I return to home, my room, familiar people, familiar places, or something that feels like belonging.' },
  5: { gravity: 'Having something or someone to be excited about has a strong effect on my mood.', retention: 'Things I made, played with, collected for fun, or associate with someone or something I loved are hardest to let go of.', rhythm: 'My hobbies, crushes, creative interests, or sources of fun can become intense and then change.', reflex: 'I create, play, flirt, perform, compete, joke, game, or find something genuinely fun.' },
  6: { gravity: 'Unfinished tasks, disorder, small problems, health concerns, or someone needing help are hard for me to ignore.', retention: 'Tools, supplies, lists, containers, remedies, spare parts, and things that might be useful later are hard for me to throw away.', rhythm: 'I repeatedly reorganize routines, lists, health habits, chores, or daily systems when I feel out of sorts.', reflex: 'I fix, clean, organize, research, make a list, or help, sometimes whether anyone asked me to or not.' },
  7: { gravity: 'The mood or response of one important person can change my own mood quickly.', retention: 'Old one-to-one bonds, message threads, gifts, and people I was once close to are hard for me to fully let go of.', rhythm: 'My emotional state rises and falls with how close or uncertain an important relationship feels.', reflex: 'I need contact, a response, or clarity about where I stand with the other person.' },
  8: { gravity: 'Trust, betrayal, secrets, dependence, jealousy, and hidden motives affect me intensely.', retention: 'Secrets, confidences, evidence, private messages, and things entrusted to me are especially hard to discard or forget.', rhythm: 'I go through intense periods of fixation, investigation, trust or distrust, followed by pulling back or starting over.', reflex: 'I investigate what is hidden, who knows what, who depends on whom, what is owed, and what could be lost.' },
  9: { gravity: 'I become restless when life feels too small or cut off from a larger idea, subject, place, or possibility.', retention: 'Books, course materials, maps, travel keepsakes, belief material, and ideas that expanded my world are hardest to let go of.', rhythm: 'I go through changing phases of fascination with big subjects, beliefs, cultures, places, or possible futures.', reflex: 'I zoom out through meaning, study, belief, travel, or imagining a larger horizon.' },
  10: { gravity: 'Being evaluated, praised, criticized, trusted, or publicly falling short affects me strongly.', retention: 'Awards, certificates, grades, finished work, praise, and other proof of accomplishment are hard for me to discard.', rhythm: 'My goals and sense of what I should become can change with feedback, recognition, disappointment, or expectations.', reflex: 'I regain my footing by finding a role, setting a goal, taking responsibility, or proving I can handle something.' },
  11: { gravity: 'Inclusion, exclusion, friendship drama, group atmosphere, and belonging affect my mood strongly.', retention: 'Old friends, contacts, group chats, communities, memberships, and shared plans are hard for me to fully let go of.', rhythm: 'My friend circles, group involvement, and future plans wax and wane in noticeable phases.', reflex: 'I reach toward friends, a group, a community, a cause, or a future plan.' },
  12: { gravity: 'My strongest reactions often arrive later and in private, after other people think the moment has passed.', retention: 'I keep private notes, dream records, old messages, hidden objects, or things whose meaning almost nobody else knows.', rhythm: 'I go through recurring periods of needing sleep, solitude, daydreaming, or disappearing from contact.', reflex: 'I withdraw, sleep, go quiet, daydream, or step outside ordinary demands until the feeling becomes clearer.' },
};

function q(prompt, a, b, c) { return { prompt, options: [a, b, c] }; }
export const DECANS = {
  aries: {
    method: q('When everyone is hesitating and something needs to start, what are you most likely to do?', 'Move first and create momentum, even if nobody has agreed on the plan yet.', 'Define the direction, take charge of the decision, and make it clear who is leading.', 'Figure out how to get the people or pieces working together so the effort can become a real result.'),
    witness: q('Which description would people who know you well be most likely to give?', 'I act quickly, push back quickly, and can be difficult to slow down once I have decided to move.', 'I naturally become visible or take the lead, and I care about having a clear say in the direction.', 'I notice who or what needs to come together, and I care about getting the effort across the finish line.'),
    predicament: q('Which kind of situation seems to follow you more often than it should?', 'I get into conflict because I moved, spoke, or decided before everyone else was ready.', 'I end up being treated as the person responsible for the direction, whether I asked for that role or not.', 'I end up trying to keep people aligned or finish something after the original excitement has worn off.'),
    distortion: q('Which criticism from people close to you sounds most familiar?', 'You can turn resistance into a fight and act before you know whether force is actually needed.', 'You can take over, make it too much about your way, or care too much about being recognized as the one in charge.', 'You can spend too much energy getting agreement, preserving the connection, or making the ending satisfying.'),
  },
  taurus: {
    method: q('When something you use starts wearing out or stops working well, what comes most naturally?', 'Figure out how it works and try to repair, improve, or adapt it.', 'Make sure I still have access to what I need, whether that means replacing it, getting another one, or managing what is available.', 'Keep it going as long as possible and avoid replacing something that still has useful life in it.'),
    witness: q('What would people who share space or belongings with you be most likely to notice?', 'I tinker, compare, measure, organize, or learn practical ways to make things work better.', 'I keep track of what we have, what is running low, who is using what, and whether there is enough.', 'I hold onto usable things for a long time and can tolerate inconvenience if it means not wasting something valuable.'),
    predicament: q('Which material problem do you seem to run into most often?', 'I can spend so much time improving the method or object that the project becomes more involved than it needed to be.', 'Questions of ownership, access, sharing, or who controls a resource become more important than I expected.', 'I stay with an old object, plan, habit, or situation long after other people think it has become too limiting.'),
    distortion: q('Which complaint about your practical side sounds most familiar?', 'You always have to adjust, optimize, fix, or figure out a better way instead of leaving something alone.', 'You can get possessive, territorial, or overly concerned with making sure resources are under control.', 'You can confuse endurance with wisdom and keep something simply because you have already kept it this long.'),
  },
  gemini: {
    method: q('When a subject really catches your mind, what do you naturally do with it?', 'Open it outward by gathering more examples, viewpoints, connections, and things to learn or explain.', 'Stress-test it by arguing with it, experimenting, finding contradictions, or seeing what survives a challenge.', 'Push toward the decisive point by finding what the whole mess is really about and what can finally be cut away or concluded.'),
    witness: q('Which description would people who talk with you a lot recognize most easily?', 'I keep adding context, links, comparisons, side paths, and new questions because one idea leads to another.', 'I question claims, challenge wording, play devil\u2019s advocate, and often find the weak spot in what someone is saying.', 'I can suddenly identify the central issue and become impatient with everything that no longer seems relevant.'),
    predicament: q('When there is too much information, which problem are you most likely to create for yourself?', 'I keep opening new lines of thought until I have too many tabs, topics, or possibilities going at once.', 'I turn the competing ideas into an argument or experiment and can keep testing long after everyone else is tired of it.', 'I reach a point where I abruptly drop, delete, dismiss, or end part of the conversation because I need the noise to stop.'),
    distortion: q('Which criticism of your thinking or communication sounds most familiar?', 'You make everything branch into five more things and have trouble deciding when you know enough.', 'You argue with things that did not need to become an argument and can sound sharper than you intended.', 'You can become so determined to expose the real point that you dismiss nuance, people, or possibilities too quickly.'),
  },
  cancer: {
    method: q('When someone or something matters to you, what kind of care comes most naturally?', 'Make it feel welcomed, wanted, protected, comfortable, or included.', 'Read what everyone needs, what is not being said, and how the situation has to be negotiated or managed.', 'Take it in deeply, remember the details, absorb the atmosphere, and carry the connection inside me.'),
    witness: q('Which thing would people close to you be most likely to notice?', 'I create comfort and belonging around people I care about, sometimes without anyone asking.', 'I notice emotional leverage, mixed motives, private dynamics, and who is giving or getting what in a relationship.', 'I remember emotional details for a very long time and can be strongly affected by a room, memory, family mood, or atmosphere.'),
    predicament: q('Which emotional situation seems to catch you repeatedly?', 'I become responsible for keeping someone comfortable or included and then feel hurt when the care is not returned.', 'I end up in situations where feelings, privacy, rivalry, favors, or unspoken expectations have to be carefully managed.', 'I absorb so much of a person, place, or situation that I eventually need to retreat before I know what is actually mine.'),
    distortion: q('Which complaint about the way you care sounds most familiar?', 'You can be overprotective, overly accommodating, or too invested in making everyone feel safe and wanted.', 'You can become secretive, strategic, suspicious, or too aware of what each person owes or wants.', 'You can hold onto moods, memories, family feelings, and old emotional material until you are saturated by it.'),
  },
  leo: {
    method: q('When you are put in a position where people are watching what you do, what brings out your strongest response?', 'Bearing the pressure, staying controlled, and proving that I cannot be pushed out of my position.', 'Growing into the attention, encouraging others, and using confidence or generosity to make the situation bigger and better.', 'Performing under pressure, competing, defending something, or showing through action that I can meet the challenge.'),
    witness: q('What would people who have seen you under pressure be most likely to say?', 'I get serious and stubborn when my ability or authority is doubted, and I can endure a lot just to prove I can.', 'I become more confident when people respond well to me and often try to lift the mood or bring other people along with my success.', 'A challenge wakes me up. Competition, performance, defense, or a chance to prove myself can make me much more forceful.'),
    predicament: q('Which kind of difficulty seems to come with being noticed?', 'Recognition feels like something I have to earn through tests, delays, resistance, or carrying more weight than other people see.', 'Praise and encouragement can make me take on more, promise more, or expect the good feeling to keep expanding.', 'Attention can turn into a contest, challenge, rivalry, or situation where I feel I have to demonstrate courage.'),
    distortion: q('Which criticism about pride or visibility sounds most familiar?', 'You can become rigid, withholding, or determined to endure something just to prove nobody can move you.', 'You can overdo confidence, generosity, promises, or the expectation that people should appreciate what you bring.', 'You can turn criticism into a competition and feel compelled to win, perform, or prove yourself in public.'),
  },
  virgo: {
    method: q('When something is messy, flawed, or unfinished, what do you notice first?', 'Why the method is not working and what needs to be understood, prepared, or done more competently.', 'What is worth keeping, what lowers the quality, and what should be edited, refined, or removed.', 'What has not been sorted, labeled, recorded, explained, checked, or actually finished.'),
    witness: q('What would people who work on things with you say you reliably contribute?', 'I diagnose problems, prepare carefully, and notice practical details that make the process work better.', 'I have strong standards about quality and can tell what should stay, what should go, and what needs more refinement.', 'I organize information, track details, clarify categories, and turn loose material into something usable and complete.'),
    predicament: q('Which kind of unfinishedness bothers you enough that you have trouble leaving it alone?', 'The process is poorly thought through or someone is doing the task without understanding how it actually works.', 'The result is cluttered, uneven, wasteful, or full of things that should have been edited out.', 'The records, labels, files, wording, categories, totals, or final details are still loose and unclosed.'),
    distortion: q('Which criticism of your standards sounds most familiar?', 'You can overanalyze, overprepare, or correct people because you need the method to make sense.', 'You can become picky, withholding, or too willing to discard something because it does not meet your standard.', 'You can get lost in lists, categories, wording, accounting, or tiny loose ends and forget that the larger job is already good enough.'),
  },
  libra: {
    method: q('When two people are at odds, what are you most likely to do first?', 'Read both people, lower the temperature, and try to restore enough reciprocity that they can deal with each other again.', 'Clarify what happened, where the boundary is, who is responsible, and what a fair rule or consequence would be.', 'Keep the discussion moving until there is a settlement both sides can understand and actually live with.'),
    witness: q('Which role would friends or classmates be most likely to see you take during a disagreement?', 'The person who notices the mood and tries to make sure everyone feels heard before things get worse.', 'The person who keeps track of what is fair, what was agreed to, and where someone crossed a line.', 'The person who wants to hear the arguments, compare them, and work out a compromise or resolution.'),
    predicament: q('Which problem do you seem to encounter when trying to make things fair?', 'I calm the situation so quickly that the real disagreement sometimes survives underneath the peace.', 'I get pulled into questions of rules, responsibility, or who owes what, and the conflict becomes more formal than I expected.', 'I keep discussing and reconsidering because I can see more than one reasonable side and want a settlement that actually holds.'),
    distortion: q('Which criticism about the way you handle conflict sounds most familiar?', 'You smooth things over or adjust yourself too quickly because you hate the feeling of open imbalance.', 'You can become rigid about fairness, keep score, or care more about the rule than how everyone is actually doing.', 'You can keep negotiating, advising, or reconsidering after everyone else wants you to choose and move on.'),
  },
  scorpio: {
    method: q('When something becomes emotionally intense or complicated, what do you most naturally do?', 'Go straight at the core of it and decide what has to be confronted, exposed, or cut away.', 'Go deeper into it until I find what is alive, true, loyal, revealing, or capable of being renewed.', 'Stay with the bond itself, following the attraction, ambiguity, desire, or emotional complexity even when it is hard to define.'),
    witness: q('Which thing would people close to you be most likely to notice?', 'When the stakes rise, I get sharper, more decisive, and much more willing to confront what other people avoid.', 'I can be intensely loyal and drawn to hidden layers of people or situations, especially when depth seems to make something stronger.', 'I can stay emotionally attached to complicated people or situations long after someone else would have wanted a clean answer.'),
    predicament: q('Which kind of intense situation seems to repeat in your life?', 'Things reach a crisis point where I feel forced to confront, break, expose, or end what cannot continue.', 'Something hidden gets revealed and I become deeply invested in whether the relationship or situation can regenerate from it.', 'Attraction, uncertainty, mixed signals, jealousy, fantasy, or emotional entanglement makes a situation much harder to leave than expected.'),
    distortion: q('Which criticism about your intensity sounds most familiar?', 'You can become ruthless, combative, or too quick to cut something off once you decide it has crossed the line.', 'Your loyalty and desire to go deeper can become fixation, pride, possessiveness, or a need to prove that the bond can survive anything.', 'You can stay attached to ambiguity, chemistry, fantasy, or complicated feelings even when clarity would make your life easier.'),
  },
  sagittarius: {
    method: q('When you discover an idea you think matters, what do you most naturally do with it?', 'Move it outward quickly by talking about it, sharing it, exploring it, arguing for it, or following where it leads.', 'Live by it and test whether I can keep believing it when circumstances become difficult.', 'Turn it into a principle, standard, commitment, system, or rule that can still matter after the excitement passes.'),
    witness: q('Which description would people who hear your opinions often recognize?', 'I get excited, talk fast, make connections, send things, suggest possibilities, and want the idea to travel.', 'I can become fiercely loyal to what experience has convinced me is true and will defend it when challenged.', 'I take beliefs seriously enough to ask what obligations, rules, authorities, or long-term consequences follow from them.'),
    predicament: q('Which problem tends to appear when you become convinced of something?', 'I spread outward so fast that I can overpromise, lose focus, or move on before the idea has been fully tested.', 'A disagreement starts feeling personal because I experience the belief as something I have had to survive or stand by.', 'The belief becomes heavy with duty, standards, or certainty, and I can feel responsible for carrying or enforcing it.'),
    distortion: q('Which criticism about your convictions sounds most familiar?', 'You can chase the next idea, place, argument, or possibility instead of staying put long enough to finish what you started.', 'You can get defensive and hold your ground because changing your mind feels too much like betraying what you have lived through.', 'You can become preachy, rigid, rule-bound, or too certain about who has the authority to define what is right.'),
  },
  capricorn: {
    method: q('When a group project or serious plan starts going badly, what are you most likely to do without being asked?', 'Find a smarter route by changing the strategy, using what is available, or making a practical deal with the situation.', 'Start doing the difficult work itself and keep building until there is something solid to show for the effort.', 'Take control of the structure by deciding priorities, assigning what needs doing, and organizing the resources or people.'),
    witness: q('Which description would people who rely on you recognize most easily?', 'I am good at spotting the workable opportunity inside a bad situation and adjusting the plan without losing the objective.', 'I am the person who keeps working, practices the skill, and carries the difficult part when a result has to be built.', 'I naturally start organizing the whole operation, including who decides, what matters most, and how everything is going to be managed.'),
    predicament: q('Which kind of responsibility seems to find you repeatedly?', 'I end up having to negotiate around limits, change the plan, or find a practical way through conditions nobody can control.', 'I end up carrying more of the actual labor than I expected because I do not trust the result unless the work is done properly.', 'I end up responsible for the whole structure because people begin looking to me to organize, decide, or keep everything under control.'),
    distortion: q('Which criticism about the way you pursue results sounds most familiar?', 'You can become too strategic or transactional, always calculating the angle, advantage, or workaround.', 'You can grind yourself down, treat everything like work, or become competitive about who is actually carrying the load.', 'You can become controlling, status-conscious, or convinced that things will fall apart unless you are the one managing them.'),
  },
  aquarius: {
    method: q('When you are part of a group that is not working well, what do you naturally do?', 'Question the shared assumptions or values and side with the people or ideas that seem more honest, even if that puts me outside the group.', 'Map how the group actually works and look for a smarter structure, process, network, or way to connect the right information.', 'Read the changing atmosphere and adjust my involvement, improvising with whoever is still participating without getting too fixed in one role.'),
    witness: q('Which description would people in your groups be most likely to recognize?', 'I am often the person who challenges the norm, forms unexpected alliances, or is willing to be unpopular over a principle.', 'I notice patterns in the system, who is connected to whom, and what process or information would make the group function better.', 'My level of involvement changes with the group\u2019s atmosphere, and I can move between being very engaged and surprisingly detached.'),
    predicament: q('Which social problem seems to repeat for you?', 'I end up at odds with the group because belonging starts to feel less important than not pretending I agree.', 'I can understand the system better than the emotional experience of the people inside it, which makes me seem detached when I am trying to help.', 'My connection to a group can change quickly with the atmosphere, leaving other people unsure how committed or involved I really am.'),
    distortion: q('Which criticism about you in groups sounds most familiar?', 'You can be contrary just because everyone else agrees, and sometimes you pay a social price that was not actually necessary.', 'You can analyze people like parts of a system and keep redesigning the process when the problem is emotional rather than technical.', 'You can seem inconsistent, hard to pin down, or halfway out the door whenever the group mood changes.'),
  },
  pisces: {
    method: q('When a situation has become too much and you cannot keep carrying it the same way, what comes most naturally?', 'Reduce what I am carrying, step back, protect my boundaries, and become quiet enough to know what has to be relinquished.', 'Open more room for feeling, imagination, compassion, beauty, connection, or possibility until the situation feels larger than the immediate pressure.', 'Make an ending real by deciding, finishing, releasing, confronting, or cutting the tie so the energy can move again.'),
    witness: q('Which description would people close to you be most likely to recognize when you are overwhelmed?', 'I withdraw, conserve energy, simplify, and become harder to reach until I know what I can and cannot continue carrying.', 'I become more receptive, imaginative, generous, emotional, or absorbed in something that lets me feel beyond the immediate problem.', 'I eventually reach a point where I need a concrete ending, release, or decisive action rather than staying suspended in the feeling.'),
    predicament: q('Which kind of ending or overwhelm seems to repeat for you?', 'I stay depleted or isolated too long because stepping back feels safer than re-entering something that already exhausted me.', 'I absorb too much, give too much room, or keep imagining possibilities until the boundaries of the situation become difficult to see.', 'Things can build until they require a dramatic finish, sacrifice, confrontation, or clean break before I feel able to begin again.'),
    distortion: q('Which criticism about the way you handle overwhelm sounds most familiar?', 'You can disappear, deny yourself too much, or withdraw so completely that nobody knows whether you are coming back.', 'You can escape into fantasy, feeling, pleasure, hope, or helping other people instead of accepting the limit that is actually there.', 'You can wait until the pressure is extreme and then make a sudden cut or ending that feels harsher than it might have needed to be.'),
  },
};
