#!/usr/bin/env python3
"""Build seven body-oriented whole-degree Timespine tables from generated degree<->UT crossings.

This is a learning harness. It does not call Swiss Ephemeris. It reads the low-resolution
crossing tables already generated by TimespineResolutionFastPOC, reconstructs the simultaneous
whole-degree celestial time of the other bodies by interval containment, discovers the smallest
non-repeating marker sets, and emits one table oriented around each body's celestial time.
"""

from __future__ import annotations

import argparse
import bisect
import csv
import itertools
import json
import struct
from collections import Counter
from pathlib import Path

BODIES = ["Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn"]
SATURN_START_JD = 2439553.3967229538

# Chosen only for this specimen. Every selected set was empirically verified to be minimal
# and non-repeating across the current Saturn vertebra. This selection also keeps the marker
# relationships distributed across all seven bodies so the resulting specimen can later be
# used to explore an internal resonator. It is not yet canonical Timespine anatomy.
SELECTED_MARKERS = {
    "Sun": ("Saturn",),
    "Moon": ("Sun", "Jupiter"),
    "Mercury": ("Moon", "Mars"),
    "Venus": ("Moon", "Mercury"),
    "Mars": ("Sun",),
    "Jupiter": ("Sun",),
    "Saturn": ("Venus",),
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser()
    p.add_argument("--input-dir", required=True, help="low-1deg directory containing *.direct-jd.bin")
    p.add_argument("--output-dir", required=True)
    return p.parse_args()


def read_direct(path: Path) -> list[tuple[float, int]]:
    data = path.read_bytes()
    if len(data) % 10:
        raise ValueError(f"{path} length is not a multiple of 10 bytes")
    rows: list[tuple[float, int]] = []
    for offset in range(0, len(data), 10):
        jd = struct.unpack_from("<d", data, offset)[0]
        degree = struct.unpack_from("<H", data, offset + 8)[0]
        rows.append((jd, degree))
    return rows


def event_direction(rows: list[tuple[float, int]], i: int) -> int:
    """Return +1 direct or -1 retrograde for a whole-degree boundary crossing.

    A station can produce the same boundary twice (entering it before the station and leaving
    it after the station). In that case use the nearest distinct neighboring boundary.
    """
    current = rows[i][1]
    for j in range(i + 1, min(len(rows), i + 5)):
        other = rows[j][1]
        if other == current:
            continue
        delta = (other - current) % 360
        if delta == 1:
            return +1
        if delta == 359:
            return -1
    for j in range(i - 1, max(-1, i - 5), -1):
        other = rows[j][1]
        if other == current:
            continue
        delta = (current - other) % 360
        if delta == 1:
            return +1
        if delta == 359:
            return -1
    raise ValueError(f"Could not determine crossing direction at row {i}")


def cell_after_crossing(rows: list[tuple[float, int]], i: int) -> int:
    degree = rows[i][1]
    direction = event_direction(rows, i)
    return degree if direction > 0 else (degree - 1) % 360


def cell_before_first_crossing(rows: list[tuple[float, int]]) -> int:
    degree = rows[0][1]
    direction = event_direction(rows, 0)
    return (degree - 1) % 360 if direction > 0 else degree


def cell_at(crossings: dict[str, list[tuple[float, int]]], times: dict[str, list[float]], body: str, jd: float) -> int:
    rows = crossings[body]
    i = bisect.bisect_right(times[body], jd) - 1
    if i < 0:
        return cell_before_first_crossing(rows)
    return cell_after_crossing(rows, i)


def build_rows(crossings: dict[str, list[tuple[float, int]]], times: dict[str, list[float]], focal: str):
    rows = []
    occurrence_by_degree: Counter[int] = Counter()
    for jd, focal_degree in crossings[focal]:
        occurrence_by_degree[focal_degree] += 1
        simultaneous = {
            body: cell_at(crossings, times, body, jd)
            for body in BODIES
            if body != focal
        }
        rows.append({
            "focalDegree": focal_degree,
            "occurrence": occurrence_by_degree[focal_degree],
            "utJulianDay": jd,
            "utOffsetSeconds": int(round((jd - SATURN_START_JD) * 86400.0)),
            "simultaneous": simultaneous,
        })
    return rows


def collision_count(rows, markers: tuple[str, ...]) -> tuple[int, int]:
    keys = Counter(
        (row["focalDegree"],) + tuple(row["simultaneous"][m] for m in markers)
        for row in rows
    )
    repeated_keys = sum(1 for n in keys.values() if n > 1)
    repeated_rows = sum(n for n in keys.values() if n > 1)
    return repeated_keys, repeated_rows


def discover_minimal_marker_sets(rows, focal: str) -> list[tuple[str, ...]]:
    others = [b for b in BODIES if b != focal]
    for size in range(1, len(others) + 1):
        winners = []
        for markers in itertools.combinations(others, size):
            repeated_keys, _ = collision_count(rows, markers)
            if repeated_keys == 0:
                winners.append(markers)
        if winners:
            return winners
    return []


def graph_reaches_all(selected: dict[str, tuple[str, ...]]) -> bool:
    for start in BODIES:
        seen = set()
        stack = [start]
        while stack:
            node = stack.pop()
            for nxt in selected[node]:
                if nxt not in seen:
                    seen.add(nxt)
                    stack.append(nxt)
        if len(seen) != len(BODIES):
            return False
    return True


def main() -> None:
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    crossings = {body: read_direct(input_dir / f"{body}.direct-jd.bin") for body in BODIES}
    times = {body: [jd for jd, _ in crossings[body]] for body in BODIES}
    all_rows = {body: build_rows(crossings, times, body) for body in BODIES}

    summary = {
        "status": "Seven body-oriented whole-degree learning specimen; no Ephemeris query during assembly",
        "saturnStartJulianDayUT": SATURN_START_JD,
        "orientation": "Each table is organized by the focal body's celestial time (whole-degree boundary). Each occurrence is bound to civic UT and stores only the selected simultaneous celestial-time marker degrees.",
        "selectedMarkerNetworkIsStronglyConnected": graph_reaches_all(SELECTED_MARKERS),
        "tables": {},
    }

    for focal in BODIES:
        rows = all_rows[focal]
        minimal = discover_minimal_marker_sets(rows, focal)
        selected = SELECTED_MARKERS[focal]
        if selected not in minimal:
            raise RuntimeError(f"Selected marker set for {focal} is not empirically minimal: {selected}; minimal={minimal}")
        repeated_keys, repeated_rows = collision_count(rows, selected)
        if repeated_keys:
            raise RuntimeError(f"Selected marker set for {focal} repeats: {repeated_keys} keys / {repeated_rows} rows")

        csv_path = output_dir / f"{focal}.csv"
        marker_columns = [f"{m}Degree" for m in selected]
        with csv_path.open("w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["focalDegree", "occurrence", "utJulianDay", "utOffsetSeconds", *marker_columns])
            for row in rows:
                writer.writerow([
                    row["focalDegree"],
                    row["occurrence"],
                    f"{row['utJulianDay']:.12f}",
                    row["utOffsetSeconds"],
                    *[row["simultaneous"][m] for m in selected],
                ])

        fixed_width_bytes = len(rows) * (4 + 2 * len(selected))
        packed_bytes = len(rows) * (5 if len(selected) == 1 else 6)
        summary["tables"][focal] = {
            "rows": len(rows),
            "selectedMarkers": list(selected),
            "minimalMarkerSets": [list(x) for x in minimal],
            "repeatedKeys": repeated_keys,
            "repeatedRows": repeated_rows,
            "simpleFixedWidthBytes": fixed_width_bytes,
            "possiblePackedBytes": packed_bytes,
        }

    summary["simpleFixedWidthBytesTotal"] = sum(x["simpleFixedWidthBytes"] for x in summary["tables"].values())
    summary["possiblePackedBytesTotal"] = sum(x["possiblePackedBytes"] for x in summary["tables"].values())

    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")

    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
